"""initial schema

Revision ID: a60bd3c4b4c3
Revises: 
Create Date: 2026-07-30 16:23:23.625374
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'a60bd3c4b4c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('slug', sa.String(length=400), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sections.id'], name=op.f('fk_sections_parent_id_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('parent_id', 'slug', name='uq_sections_parent_id_slug')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index('ix_sections_parent_id', ['parent_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('tag', 'research_category', name='tag_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('kind', 'slug', name='uq_tags_kind_slug')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_kind', ['kind'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('seed_id', sa.Integer(), nullable=True),
    sa.Column('date_text', sa.String(length=300), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('date_precision', sa.Enum('day', 'month', 'month-range', 'season', 'year', 'year-range', 'range', 'approx', 'undated', name='date_precision', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subsection_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('published', 'retracted', name='event_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_from_submission_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('date_end IS NULL OR date_start IS NULL OR date_end >= date_start', name=op.f('ck_events_date_end_after_start')),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('fk_events_section_id_sections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subsection_id'], ['sections.id'], name=op.f('fk_events_subsection_id_sections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_events_dedup_key')),
    sa.UniqueConstraint('external_id', name=op.f('uq_events_external_id'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_date_start', ['date_start'], unique=False)
        batch_op.create_index('ix_events_section_id', ['section_id'], unique=False)
        batch_op.create_index('ix_events_status_date_start', ['status', 'date_start'], unique=False)
        batch_op.create_index('ix_events_subsection_id', ['subsection_id'], unique=False)

    op.create_table('event_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_sources_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_event_sources_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_sources')),
    sa.UniqueConstraint('event_id', 'source_id', 'url', name='uq_event_sources_event_id_source_id_url')
    )
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.create_index('ix_event_sources_source_id', ['source_id'], unique=False)

    op.create_table('event_tags',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_tags_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_event_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name=op.f('pk_event_tags'))
    )
    with op.batch_alter_table('event_tags', schema=None) as batch_op:
        batch_op.create_index('ix_event_tags_tag_id_event_id', ['tag_id', 'event_id'], unique=False)

    op.create_table('pending_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_type', sa.Enum('new', 'edit', name='submission_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'auto_closed', name='submission_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('target_event_id', sa.Integer(), nullable=True),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('scraper', sa.String(length=200), nullable=False),
    sa.Column('scraper_run_id', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('proposed', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('edited_by_reviewer', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('applied', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('resulting_event_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(submission_type = 'edit' AND target_event_id IS NOT NULL) OR submission_type = 'new'", name=op.f('ck_pending_submissions_edit_requires_target')),
    sa.ForeignKeyConstraint(['resulting_event_id'], ['events.id'], name=op.f('fk_pending_submissions_resulting_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_event_id'], ['events.id'], name=op.f('fk_pending_submissions_target_event_id_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_submissions'))
    )
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_pending_submissions_dedup_key', ['dedup_key'], unique=False)
        batch_op.create_index('ix_pending_submissions_scraper', ['scraper'], unique=False)
        batch_op.create_index('ix_pending_submissions_status_submitted_at', ['status', 'submitted_at'], unique=False)
        batch_op.create_index('ix_pending_submissions_target_event_id', ['target_event_id'], unique=False)
        batch_op.create_index('uq_pending_submissions_open_dedup_key', ['dedup_key'], unique=True, sqlite_where=sa.text("status IN ('pending', 'auto_closed')"), postgresql_where=sa.text("status IN ('pending', 'auto_closed')"))

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('seed.import', 'submission.received', 'submission.corroborated', 'submission.auto_closed', 'submission.approved', 'submission.rejected', 'event.created', 'event.updated', 'event.retracted', name='audit_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('event_version', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_audit_log_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['pending_submissions.id'], name=op.f('fk_audit_log_submission_id_pending_submissions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_event_id_occurred_at', ['event_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_log_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_log_submission_id', ['submission_id'], unique=False)

    op.create_table('submission_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('scraper', sa.String(length=200), nullable=False),
    sa.Column('scraper_run_id', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_summary', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['pending_submissions.id'], name=op.f('fk_submission_evidence_submission_id_pending_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_evidence'))
    )
    with op.batch_alter_table('submission_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_submission_evidence_submission_id', ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_evidence_submission_id')

    op.drop_table('submission_evidence')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_submission_id')
        batch_op.drop_index('ix_audit_log_occurred_at')
        batch_op.drop_index('ix_audit_log_event_id_occurred_at')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_index('uq_pending_submissions_open_dedup_key', sqlite_where=sa.text("status IN ('pending', 'auto_closed')"), postgresql_where=sa.text("status IN ('pending', 'auto_closed')"))
        batch_op.drop_index('ix_pending_submissions_target_event_id')
        batch_op.drop_index('ix_pending_submissions_status_submitted_at')
        batch_op.drop_index('ix_pending_submissions_scraper')
        batch_op.drop_index('ix_pending_submissions_dedup_key')

    op.drop_table('pending_submissions')
    with op.batch_alter_table('event_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_event_tags_tag_id_event_id')

    op.drop_table('event_tags')
    with op.batch_alter_table('event_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_event_sources_source_id')

    op.drop_table('event_sources')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_subsection_id')
        batch_op.drop_index('ix_events_status_date_start')
        batch_op.drop_index('ix_events_section_id')
        batch_op.drop_index('ix_events_date_start')

    op.drop_table('events')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_kind')

    op.drop_table('tags')
    op.drop_table('sources')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index('ix_sections_parent_id')

    op.drop_table('sections')
    # ### end Alembic commands ###
